FROM debian:buster

RUN apt-get update
RUN apt-get upgrade -y


RUN apt-get install -y vim
RUN apt-get install -y wget
RUN apt-get install -y nginx
RUN apt-get install -y curl

RUN apt-get -y install php7.3
RUN apt-get -y install php7.3-fpm

ARG src_dir="nginx/test/"

ARG file1="1-multiple_servers_different_ports.conf"
ARG file2="2-index_server_not_location.conf"
ARG file3="3-same_port_different_names.conf"
ARG file4="4-default_error_pages.conf"
ARG file5="5-body_size_limit.conf"
ARG file6="6-routes.conf"
ARG file7="7-indexes.conf"

ARG src=${src_dir}${file1}

# COPY nginx/default.conf /tmp/default.conf
COPY ${src} "/tmp/default.conf"

RUN rm -f var/www/html/index.nginx-debian.html
RUN rm -f var/www/html/index.html

COPY public /var/www/

COPY nginx/*.sh .
CMD bash start.sh
